

services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"  # map container's 8080 to host's 8081

volumes:
  postgres_data: